deploy:
  provider: s3
  bucket: foolhearts.com
  skip_cleanup: true
  region: us-east-1
  access_key_id: AKIAX4USGN7TMVRH4GMM
  secret_access_key:
    secure: sh7vUJyViClrVQZfUa1kggHGK7RlOH0Vop5DSiTKQnyoxfnYoDVLLTuwykiKTtYRcBd7VJ8LW5wQDlwdiAHDD4nzhl2BNPoh+qu+m7GquzuTUaDjFBS8IfKeRPVXrqNxNvTclCkm0scjN08fMA/e5O3MpY6dqEmApKX5BukJ+YWzaq6274ELr9ybIXBBwFcn8DWYk+itNc0m7Z3nKDcz+Vv/JKeQ3erooqtnlvj9/EtXYfyb1272LkQIM7LpU4nu3e+LgwIyE6zbQfddKgDk4Mfaxp4IsgXkN/xXz5BuFv8evjbabX6S+d2SveKD4fLPhX8Er4sbaNACKOZ5UMu1iAuCNvrfLpmfavHkLBbyqTQFo3KSrtRHcqqOCQL8nvwp6pNwl8erGIMMjJsyf4boTO2x/WRFBGMVHPLLq3SJlkVg9F/yuiSZji9x52/djWtwK/FzSAmv2AE0Ou2Xubj1ZAZJ0apbpbDtOE8lySTRVc5u+tR4fxVE2awKCIYlwSEqo7sENGg5PkfMqs+iGBWq/aydGuoU/+lqh+WaiBMsiTnEFCvdej4TEkIH89L2AozbOVugML812IJvQX0sAMpuDe1niQwXfMFbzc8Yj0xCXRZxbSigH+0PQ1oSjY3+2TfWlUSnxzI0t4AfVTmcBsUtEqJZBggJbMdfUpezI+wDPPA=
